XSI-915: Improve performance of LVHDoHBA operations by
xapi-project/sm pull request #535
Opened 2021-01-27 08:29 UTC by BenSimsCitrix

This commit increases performance by.

       1) Reducing expensive calls to _pathfresh
	2) Use multipath with option "-l" and then falling back to using the more expensive "-ll"
	   only if first operation it fails.
	3) Add missing vdi_epoch operations to vdi operation list

This has been through a BST.

2021-01-27 09:07 UTC, MarkSymsCtx requested changes
Remove the extraneous calls to load

2021-01-27 09:07 UTC, MarkSymsCtx commented on drivers/LVHDoHBASR.py
> +        self.load(sr_uuid)
Not required. This is called from the superclass __init__

2021-01-27 09:07 UTC, MarkSymsCtx commented on drivers/LVHDoHBASR.py
> +        self.load(sr_uuid)
Ditto

2021-01-27 09:07 UTC, MarkSymsCtx commented on drivers/LVHDoHBASR.py
> +                self.load(sr_uuid)
Ditto

2021-02-15 18:26 UTC, BenSimsCitrix commented
This has got through another BST.

2021-02-19 18:27 UTC, BenSimsCitrix commented
Pesky "iter" bug got me again this does manifest locally when i run the tests hence why i keep getting bitten, Tests are passing now

2021-02-22 15:11 UTC, MarkSymsCtx commented on tests/test_SR.py
> +    def test_checkroot_no_device(self):
Do these tests need to be asserting anything after the calls to check they functioned correctly?

2021-02-22 16:29 UTC, MarkSymsCtx approved these changes

2021-02-23 12:01 UTC, TimSmithCtx approved these changes

2021-02-23 14:02 UTC, merged