CP-38283: Support explicit NFS 4.0 version choice
xapi-project/sm pull request #571
Opened 2021-10-01 14:02 UTC by edwintorok

Setting nfsversion=4 uses either 4.0 or 4.1, depending what is
available.

It is already possible to explicitly force 4.1, add similar support for
4.0.

Explicitly choosing 4.0 can be important when trying to
diagnose potential performance regressions due to NFS versions / NFS
server changes.

Signed-off-by: Edwin Török <edvin.torok@citrix.com>

2021-10-01 14:05 UTC, MarkSymsCtx commented
Not required, the nfsversionis passed directly to the mount command - https://github.com/xapi-project/sm/blob/master/drivers/nfs.py#L151

2021-10-01 14:10 UTC, MarkSymsCtx requested changes
As Andy says, use startswith.

2021-10-01 14:14 UTC, MarkSymsCtx commented
In fact actually, drop most of this code as it's not necessary.
```
Under Linux 2.6.32 and later kernel versions, mount.nfs can mount all NFS file system versions.
```
So, since ancient times calling `mount.nfs4` has been unnecessary

2021-10-01 14:16 UTC, MarkSymsCtx commented on drivers/nfs.py
> +    if nfsversion in ['4', '4.0', '4.1']:
Remove entirely and just call `mount.nfs` always

2021-10-01 14:17 UTC, MarkSymsCtx submitted a review, later dismissed

2021-10-01 14:18 UTC, edwintorok commented
Do we want to use startswith 4. for nfsversion in general? That'd allow us to force 4.2 as soon as the kernel and the NFS server begins supporting it without further changes needed here.

2021-10-01 14:18 UTC, edwintorok commented
need to update unit test

2021-10-01 14:25 UTC, MarkSymsCtx commented
> Do we want to use 3 || startswith 4. for nfsversion in general? That'd allow us to force 4.2 as soon as the kernel and the NFS server begins supporting it without further changes needed here.
Yes, I think so, but we should also upgrade a bare "4" to be 4.1 until 4.2 is specifically supported.

2021-10-01 14:29 UTC, edwintorok commented
ok I'll add that as a commit on top

2021-10-01 14:45 UTC, edwintorok commented
I've added 4.x support, haven't updated the help message at the top, since we don't support 4.2 yet.

2021-10-01 14:48 UTC, MarkSymsCtx approved these changes

2021-10-04 13:16 UTC, TimSmithCtx approved these changes

2021-10-04 14:40 UTC, merged