QNAP product attribute is incorrect
xapi-project/sm pull request #576
Opened 2021-11-18 12:17 UTC by a573net

Hello,

I found an incorrect QNAP entry in multipath.conf.
The product attribute was "iSCSI_Storage", but the actual QNAP product attribute was "iSCSI Storage". Underscores should be spaces.

I suggested writing 2 blocks of underscore and space in the forum below.
Please check the forum below for details.
https://xcp-ng.org/forum/topic/5194/multipath-conf-is-incorrect

I was suggested by forum users to give feedback to the fork source.

I use multipathing with iSCSI in QNAP.
Because of the different multipath speeds, I had to set a fixed priority.
I noticed this mistake with the multipath -ll command and posted.

2021-11-18 14:36 UTC, MarkSymsCtx commented
Two things

- You need to sign off the commit for DCO, do `git commit --amend -s` and then force push to your branch
- This should replace the incorrect block of configuration instead of creating a new one

2021-11-18 14:37 UTC, MarkSymsCtx requested changes
Two things

You need to sign off the commit for DCO, do git commit --amend -s and then force push to your branch
This should replace the incorrect block of configuration instead of creating a new one

2021-11-18 14:39 UTC, olivierlambert commented
Do we know if QNAP changed their product attribute or the `iSCSI_Storage` was wrong since the start?

2021-11-18 14:55 UTC, MarkSymsCtx commented
> Do we know if QNAP changed their product attribute or the `iSCSI_Storage` was wrong since the start?

I suspect wrong from the start

2021-11-18 14:57 UTC, olivierlambert commented
So in that case indeed, it's best to modify it instead of adding it (if it's wrong from the start, it means there's no chances to break something existing/used)

2021-11-19 02:20 UTC, a573net commented
I am not used to operating github.
I have operated several times.
I'm sorry.

2021-11-19 09:03 UTC, MarkSymsCtx requested changes
That's still wrong, you still have two copies of the QNAP configuration.

2021-11-19 09:04 UTC, MarkSymsCtx commented
And you need to clean up the commit history, read up on `git rebase` - https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History

2021-11-20 00:48 UTC, a573net commented
Everyone, please help me.
I'm not sure. I can't rebase well.
I think you should delete # 576 itself.
Please tell me how to do it.

2021-11-20 00:51 UTC, a573net commented
If you can close this # 576 with the authority of the master, please close it.

2021-11-20 00:58 UTC, a573net commented
I'm sorry for sending multiple messages.
I use the web interface.
Can I delete # 576 with "**Close pull request**" under this comment field?

2021-11-25 17:07 UTC, MarkSymsCtx commented
I've done the rebasing required here but you still need to sign-off the commit. Do the following from where have the code checked out. (assuming that your git origin is your fork, if not change origin to the name of your fork's remote)
```
git checkout patch-2
git reset --hard origin/patch-2
git commit -s --amend
git push origin patch-2 -f
```

2021-11-25 17:07 UTC, MarkSymsCtx approved these changes

2021-11-27 00:50 UTC, a573net commented
Thank you very much for helping me.
I executed the command you told me.
Please check status.

2021-11-29 16:53 UTC, MarkSymsCtx approved these changes

2021-11-29 17:11 UTC, edwintorok approved these changes
The commit message has some duplication (copy/paste or squashing issue?), but the change itself looks fine.

2021-11-29 17:19 UTC, MarkSymsCtx commented
> The commit message has some duplication (copy/paste or squashing issue?), but the change itself looks fine.

a573net, if you want to do another `git commit --amend` and update the comment to remove the duplication then that's fine otherwise it's fine as it is with the message duplicated.

2021-11-30 05:28 UTC, a573net commented
> a573net, if you want to do another `git commit --amend` and update the comment to remove the duplication then that's fine otherwise it's fine as it is with the message duplicated.

I am not familiar with git, so I am not confident in the operation. The message column is dirty, but I want to finish it as it is. If you have to change it, tell me the git command.
Thank you for helping me.

2021-11-30 08:52 UTC, stormi commented
You'd do:
```
git commit --amend
```
Edit the message in the editor that opens.

Then:
```
git push --force-with-lease
```

2021-11-30 09:25 UTC, a573net commented
Thank you for helping me.
I corrected the message. Please check.

2021-11-30 10:52 UTC, rosslagerwall approved these changes

2021-12-01 15:28 UTC, MarkSymsCtx commented
Sorry, to be a pain but as this goes into the history of the code can you make one more small change to the commit message and change the first line to a brief summary of the change? Something like
```
Update product identification for QNAP iSCSI storage
```
And then make the rest a bit less like an email, removing the initial `Hello, ` will be sufficient for that.

2021-12-01 23:23 UTC, a573net commented
Thank you for following me.
I summarized the comments.
Please check.

2021-12-01 23:25 UTC, a573net commented
Oops.
I accidentally deleted the signoff line for DCO.

2021-12-02 09:25 UTC, MarkSymsCtx approved these changes

2021-12-02 16:36 UTC, rosslagerwall approved these changes

2021-12-13 12:36 UTC, a573net commented
Do I need to operate something? Should I wait without doing anything?

2021-12-13 12:40 UTC, olivierlambert commented
IMHO, I think now it's just waiting for 2 other reviews, so it looks that you don't need to do anything else :)

2021-12-13 12:54 UTC, TimSmithCtx approved these changes

2021-12-13 12:57 UTC, merged

2021-12-13 13:02 UTC, olivierlambert commented
Congrats and thank you @a573net for your contribution :partying_face:

2021-12-15 05:48 UTC, a573net commented
Thank you for your cooperation!